### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dbr96** [kmb266/cs5150-basketball-project#13]
https://github.com/kmb266/cs5150-basketball-project/blob/37a68d206d91ba7208e61c851fe2e65c8e60493b/app/advanced_stat.py#L1082

I think I typed this wrong. ORE is supped to be OREB, offensive rebound. (this particular advanced stat is also not super important). this may also not even matter.

**Comment by kmb266** [comment]
it should not break anything because it has the same typo when referencing that parameter (parameters are the test inside the () on the def line (e.g. PTS, or FGA, or ORE) and because 2 lines down it also says ORE, it is fine

**Comment by kmb266** [comment]
I can still change it though for consistency
