### ISSUE TITLE
Line 184

### ISSUE THREAD

**Issue by dbr96** [kmb266/cs5150-basketball-project#7]
https://github.com/kmb266/cs5150-basketball-project/blob/37a68d206d91ba7208e61c851fe2e65c8e60493b/app/advanced_stat.py#L184

There might be an extra parenthesis. I can't tell.

**Comment by kmb266** [comment]
how does this number compare to your spreadsheet number for PProdOREB? if it is the same, then it should not be missing a parenthesis.
I suggest doing some dummy numbers for the inputs like do all 1's then do 1,2,3 etc. to see if it returns the same number

**Comment by dbr96** [comment]
Ran some numbers. got the same result. Parentheses are fine.
