### ISSUE TITLE
FGPart

### ISSUE THREAD

**Issue by dbr96** [kmb266/cs5150-basketball-project#8]
https://github.com/kmb266/cs5150-basketball-project/blob/37a68d206d91ba7208e61c851fe2e65c8e60493b/app/advanced_stat.py#L252

Might be an extra parenthesis. I don't think it affects the formula nor outcome but I'm not 100% sure.

**Comment by kmb266** [comment]
if you are talking about the `((PTS-FTM))` with double parenthesis -- It should not mess anything up
